name: cyber_sentinel
description: A cybersecurity monitoring tool
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.1
  intl: ^0.18.1
  font_awesome_flutter: ^10.5.0
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
